export const Users = [
    {
        "id": 1,
        "name": "saurabh",
        "company_name": "HP",
        "email": "saurabhkumar@gmail.com",
        "zipcode": "2340",
    },
    {
        "id": 2,
        "name": "Suhan",
        "company_name": "smart_dental",
        "email": "suhankhan@gmail.com",
        "zipcode": "6346",
    },
    {
        "id": 3,
        "name": "Babu",
        "company_name": "yahoo",
        "email": "babukhan@yahoo.com",
        "zipcode": "4553",
    },
    {
        "id": 4,
        "name": "owasim",
        "company_name": "PowerGrid",
        "email": "owasimkhan@gmail.com",
        "zipcode": "7777",
    },
    {
        "id": 5,
        "name": "Badhon",
        "company_name": "Central_bank",
        "email": "badhonkhan@gmail.com",
        "zipcode": "98765"
        , },
    {
        "id": 6,
        "name": "Mainul",
        "company_name": "Tex_zipper",
        "email": "mainul@gmail.com",
        "zipcode": "3537",
    },
    {
        "id": 7,
        "name": "Rafat",
        "company_name": "Facebook",
        "email": "rafatulaman@gmail.com",
        "zipcode": "87666",
    },
    {
        "id": 8,
        "name": "Sirajul",
        "company_name": "Google",
        "email": "itsirajul@gmail.com",
        "zipcode": "6326",
    },
    {
        "id": 9,
        "name": "Tushar",
        "company_name": "Walton",
        "email": "tufayel123@gmail.com",
        "zipcode": "5437",
    },
    {
        "id": 10,
        "name": "Payel",
        "company_name": "Amazon",
        "email": "payel334@gmail.com",
        "zipcode": "46982"
        , },
    {
        "id": 11,
        "name": "Rakib",
        "company_name": "Mangrove_IT",
        "email": "khanrakib218@gmail.com",
        "zipcode": "1188",
    },
    {
        "id": 12,
        "name": "Tayem",
        "company_name": "Flipcart",
        "email": "Tayem@gmail.com",
        "zipcode": "6543",
    },
    {
        "id": 13,
        "name": "Nasim",
        "company_name": "Xiaomi",
        "email": "nasim4455@gmail.com",
        "zipcode": "8461",
    },
    {
        "id": 14,
        "name": "Arafat",
        "company_name": "City_Bank",
        "email": "arafathosain@gmail.com",
        "zipcode": "57654",
    },
    {
        "id": 15,
        "name": "Mehedi",
        "company_name": "Apple",
        "email": "Mehedihasan@gmail.com",
        "zipcode": "84579"
        , },
    {
        "id": 16,
        "name": "Rimel",
        "company_name": "Burger_King",
        "email": "Rimelkhan@gmail.com",
        "zipcode": "3467",
    },
    {
        "id": 17,
        "name": "Dhiman",
        "company_name": "Snapdragon",
        "email": "dhimanislam@gmail.com",
        "zipcode": "64387",
    },
    {
        "id": 18,
        "name": "Imran",
        "company_name": "Dell",
        "email": "imranhossain@gmail.com",
        "zipcode": "73934",
    },
    {
        "id": 19,
        "name": "Riad",
        "company_name": "Qualcom",
        "email": "imtiazriad@gmail.com",
        "zipcode": "7777",
    },
    {
        "id": 20,
        "name": "ishraf",
        "company_name": "Mangrove_IT",
        "email": "ishraf.hb@mangroveitsoftware.com",
        "zipcode": "98765"
        , },
]